npm install
npm run make:prepare
HUGO_VERSION=0.71.1 npm run serve

[build]
  command = "hugo"
  context = "production"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.78.0"
  HUGO_ENV = "production"