[build]
publish = "stevenzhujr/public"
command = "hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.111.3"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
